---
binance_api: 
  key:
    vzqtv0jy0JiT8CyqDUSYL3HGlKy7pKDMKyV7Zlqj0jEaF2IO0w83E3r2DDA24dIu
  secret:
    fkjzo9OEgam4l4JJlYoSWxEZl0nYcZjaFMZ1Ky1peZd1OKpc8babalsf1SkSdDAh

gmail:
  user:
    sixjuwel
  password:
    sflknedbfeqinjzi